version: 2.1

# List of all environment variables accessible in this config file
# https://circleci.com/docs/2.0/env-vars/#built-in-environment-variables

# Recommendations
# ---------------

# General Principles:
#
#  1. Descriptive: The job name should clearly describe what the job does.
#  2. Concise: Names should be as short as possible while still being descriptive.
#  3. Consistent: Use a consistent format or pattern for all job names.
#  4. Avoid Ambiguous Abbreviations: If you use abbreviations, ensure they are widely understood.
#
# Naming Convention Proposal:
#
#  1. Prefixes based on the nature of the job:
#     - build-: for jobs related to building or installation.
#     - lint-: for jobs related to code quality checking.
#     - test-: for jobs related to testing.
#     - security-: for jobs related to security.
#     - metrics-: for jobs related to metrics generation.
#     - deploy-: for jobs related to deployment.
#     - notify-: for jobs related to notifications.
#     - debug-: for jobs related to debugging.
#     - setup-: for jobs related to set up.
#     - init-: for jobs related to initialization.
#     - generate-: for jobs related to generation.
#     - validate-: for jobs related to validation.
#     - compile-: for jobs related to compilation.
#     - e2e-: for jobs related to end-to-end testing.
#
#  2. Suffixes based on the specific tool or task:
#  For example, for a job that uses PHP_CodeSniffer, use phpcs as a suffix.


# Default configuration for persist_to_workspace and attach_workspace commands
persist_to_workspace: &persist_to_workspace
  persist_to_workspace:
    root: .
    paths:
      - .

attach_workspace: &attach_workspace
  attach_workspace:
    # Must be absolute path or relative path from working_directory
    at: ~/project

# This main executor is used by all jobs unless otherwise specified
executors:
  php-executor:
    resource_class: small
    shell: /bin/bash
    docker:
      - name: localhost
        image: cimg/php:8.3
  builder-executor:
    resource_class: small
    shell: /bin/bash
    docker:
      - image: cimg/php:8.3-node
        name: localhost
  simple-executor:
    resource_class: small
    shell: /bin/bash
    docker:
      - image: cimg/base:stable
        name: localhost



jobs:
  debug-info:
    executor: php-executor
    steps:
      - run:
          name: Debug
          command: |
            echo "Current user: $USER"
            echo "Home directory: $HOME"
            echo "Current shell: $SHELL"
            echo "Operating system: $(uname -a)"
            echo "Current path: $PATH"
            echo "Current working directory: $(pwd)"
            echo "Current date: $(date)"
            echo "--------------------"
            env

  build-setup:
    executor: php-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: composer install --no-interaction --no-ansi --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - *persist_to_workspace

  lint-phpcs:
    executor: php-executor
    steps:
      - *attach_workspace
      - run:
          name: Install PHP_CodeSniffer and PHPCompatibility
          command: composer require --dev "squizlabs/php_codesniffer=*" "phpcompatibility/php-compatibility=*"
      - run:
          name: Run PHP_CodeSniffer with Custom Ruleset in the project root
          command: |
            ./vendor/bin/phpcs --standard=phpcs.xml --report-file=phpcs-report.txt --report=checkstyle --extensions=php --ignore=vendor/ .
            result=$?
            if [ $result -eq 1 ] || [ $result -eq 2 ]; then
              exit 0
            else
              exit $result
            fi
      - store_artifacts:
          path: phpcs-report.txt
          destination: phpcs-report

  # how to exploi--> a améliorer et à mettre dans les axes cyber
  metrics-phpmetrics:
    executor: php-executor
    steps:
      - *attach_workspace
      - run:
          name: Install PHP Metrics
          command: composer require --dev phpmetrics/phpmetrics
      - run:
          name: Run PHP Metrics
          command: |
            ./vendor/bin/phpmetrics --exclude=vendor,tmp --report-html=phpmetrics-report.html ./src
      - store_artifacts:
          path: phpmetrics-report.html
          destination: phpmetrics-report

  #how to exploit ?
  metrics-phploc:
    executor: php-executor
    steps:
      - *attach_workspace
      - run:
          name: Download phploc.phar
          command: |
            wget https://phar.phpunit.de/phploc.phar
            echo "expected-sha256 phploc.phar" | sha256sum -c -
            chmod +x phploc.phar
      - run:
          name: Run phploc
          command: |
            php phploc.phar ./src > phploc-report.txt
      - run:
          name: Check Cyclomatic Complexity
          command: |
            class_complexity=$(grep "Average Complexity per Class" phploc-report.txt | awk '{print $5}')
            method_complexity=$(grep "Average Complexity per Method" phploc-report.txt | awk '{print $5}')
            if [ $(echo "$class_complexity > 10" | bc) -eq 1 ]; then
              echo "Warning: Cyclomatic complexity for classes is too high ($class_complexity)."
              exit 1
            fi
            if [ $(echo "$method_complexity > 5" | bc) -eq 1 ]; then
              echo "Warning: Cyclomatic complexity for methods is too high ($method_complexity)."
              exit 1
            fi
      - store_artifacts:
          path: phploc-report.txt
          destination: phploc-report

  # rendre rapport plus joli
  lint-phpmd:
    executor: php-executor
    steps:
      - *attach_workspace
      - run:
          name: Install PHP Mess Detector in CI environment
          command: composer require --dev phpmd/phpmd
      - run:
          name: Analyse code with PHP Mess Detector
          command: |
            ./vendor/bin/phpmd ./ text cleancode,codesize,controversial,design,naming,unusedcode --suffixes=php --exclude vendor,tmp > phpmd-report.txt
            result=$?
            if [ $result -eq 1 ] || [ $result -eq 2 ]; then
              exit 0
            else
              exit $result
            fi
      - store_artifacts:
          path: phpmd-report.txt
          destination: phpmd-report

  gate-quality-check:
    executor: simple-executor
    steps:
      - run:
          name: Check Quality Reports
          command: |
            if [ -f "phpmd-report.txt" ] || [ -f "phpcs-report.txt" ]; then
              echo "All reports are clean."
            else
              echo "Quality check issues found. Generating an alert log."
              echo "QUALITY CHECK FAILED: Issues found in PHP quality reports." > quality-alert.log
            fi
      - store_artifacts:
          path: quality-alert.log
          destination: alerts/quality-check
  
  quality-approval:
    type: approval
    requires:
      - gate-quality-check
        
  #Outil pas très utile
  lint-php-doc-check:
    executor: php-executor
    steps:
      - *attach_workspace
      - run:
          name: Install PHP Doc Check
          command: composer require --dev niels-de-blaauw/php-doc-check
      - run:
          name: Run PHP Doc Check
          command: |
            ./vendor/bin/php-doc-check ./ --format=text --exclude=vendor --reportFile=php-doc-report.txt --complexity-error-threshold=6 --complexity-warning-threshold=5
            result=$?
            if [ $result -eq 1 ] || [ $result -eq 2 ]; then
              exit 0
            else
              exit $result
            fi
      - store_artifacts:
          path: php-doc-report.txt
          destination: php-doc-report

  #pas utile
  security-check-dependencies:
    executor: php-executor
    steps:
      - *attach_workspace
      - run:
          name: Download and verify local-php-security-checker
          command: |
            # Télécharger l'outil
            curl -L -o local-php-security-checker https://github.com/fabpot/local-php-security-checker/releases/download/v2.1.3/local-php-security-checker_linux_amd64

            # Télécharger le fichier de checksum
            curl -L -o local-php-security-checker.sha256 https://github.com/fabpot/local-php-security-checker/releases/download/v2.1.3/local-php-security-checker_linux_amd64.sha256

            # Valider l'authenticité du fichier téléchargé
            echo "Vérification du checksum SHA256..."
            sha256sum -c local-php-security-checker.sha256 || (echo "Checksum invalide !"; exit 1)

            # Rendre l'outil exécutable
            chmod +x local-php-security-checker
      - run:
          name: Check Dependencies
          command: ./local-php-security-checker --format=json > security-report.json
      - run:
          name: Check for Critical Vulnerabilities
          command: |
            # Si des vulnérabilités critiques sont trouvées, échouer le job
            if grep '"severity": "critical"' security-report.json; then
              echo "Critical vulnerability found. Failing the job."
              exit 1  # Le job échoue ici si une vulnérabilité critique est trouvée
            else
              echo "No critical vulnerabilities found."
            fi
      - store_artifacts:
          path: security-report.json
          destination: security-report

  test-phpunit:
    executor: php-executor
    steps:
      - *attach_workspace
      - run:
          name: Check if PHPUnit tests are present, otherwise skip the job
          command: |
            if [ ! -f "phpunit.xml" ]; then
              echo "No PHPUnit tests found, skipping job."
              echo "export SKIP_PHPUNIT=true" >> $BASH_ENV
              circleci step halt
            fi
      - run:
          name: Install PHPUnit
          command: composer require --dev phpunit/phpunit
      - run:
          name: Run PHPUnit
          command: ./vendor/bin/phpunit --testsuite=Unit

  lint-outdated-dependencies:
    executor: php-executor
    steps:
      - run:
          name: Check for Outdated Dependencies
          command: composer outdated

  build-docker-image:
    executor: builder-executor
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Build and Push Docker Image to GHCR (GitHub Container Registry)
          command: |
            if [ ! -z "$SKIP_BUILD" ]; then
              echo "Skipping build"
              circleci step halt
              exit 0
            fi

            # Sanitize the repository name and branch name
            REPOSITORY=$(echo "ghcr.io/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME" | tr '[:upper:]' '[:lower:]' | tr -d '_')
            REPOSITORY="$REPOSITORY/phpapp"
            TAG=$(echo $CIRCLE_BRANCH | tr '[:upper:]' '[:lower:]' | tr '/' '-' | tr -cd '[:alnum:]._-' | cut -c 1-128)

            # Login to GHCR
            echo "$GHCR_PAT" | docker login ghcr.io -u "$GHCR_USERNAME" --password-stdin

            # Build the Docker image
            docker build -t ghcr.io/yvannponce/php-devsecops/phpapp:${CIRCLE_SHA1} --build-arg TAG="${CIRCLE_SHA1}" .

            # Push the Docker image
            docker push ghcr.io/yvannponce/php-devsecops/phpapp:${CIRCLE_SHA1}


  deploy-ssh-staging:
    executor: simple-executor
    steps:
      - add_ssh_keys:
          fingerprints:
            - "${STAGING_SSH_FINGERPRINT}"
      - deploy:
          name: Deploy to AWS
          command: |
            set -x
            ssh -o StrictHostKeyChecking=no $STAGING_SSH_USER@$STAGING_SSH_HOST \<< EOF
            PHP_FPM_VERSION=$(php -v | head -n 1 | cut -d ' ' -f 2 | cut -d '.' -f 1-2)
            cd $STAGING_DEPLOY_DIRECTORY
            git pull origin $CIRCLE_BRANCH
            composer install --optimize-autoloader --no-interaction --prefer-dist
            (flock -w 10 9 || exit 1; sudo -S service php${PHP_FPM_VERSION}-fpm restart ) 9>/tmp/fpm.lock
            EOF


#  deploy-ssh-production:
# It's up to you :)


workflows:
  main_workflow:
    jobs:
      - debug-info
      - build-setup
      - lint-outdated-dependencies:
          requires:
            - build-setup
      - lint-phpcs:
          requires:
            - build-setup
      - metrics-phpmetrics:
          requires:
            - build-setup
      - metrics-phploc:
          requires:
            - build-setup
      - lint-phpmd:
          requires:
            - build-setup
      - gate-quality-check:
          requires:
            - lint-phpcs
            - lint-phpmd
      - quality-approval:
          requires:
            - gate-quality-check
      - lint-php-doc-check:
          requires:
            - build-setup
      - security-check-dependencies:
          requires:
            - build-setup
      - test-phpunit:
          requires:
            - build-setup
      # - deploy-ssh-production:
      #     requires:
      #         - hold
      #     filters:
      #       branches:
      #         only:
      #           - main
      #           - master
      #- deploy-ssh-staging:
      #    requires:
      #      - hold
      #    filters:
      #      branches:
      #        only:
      #          - /^release\/.*/


  container_workflow:
    jobs:
      - build-docker-image:
          filters:
            branches:
              only:
                - master
                - main
                - develop
                - /^feature\/.*/
                - /^release\/.*/
                - /^hotfix\/.*/
                - /^bugfix\/.*/